# Lint as: python3
"""Convert a PPTS file into a schemaless csv.

If you run this with a single arg, it will just dump the PPTS file to a
schemaless csv. If you provide two args, it will diff against an existing
schemaless csv.
"""

import argparse
import csv
from csv import DictReader
from datetime import date
import lzma
import sys
import uuid



def just_dump(ppts_file, outfile):
    if ppts_file.endswith('.xz'):
        o = lzma.open
    else:
        o = open
    with o(ppts_file, mode='rt', encoding='utf-8', errors='replace') as inf:
        reader = DictReader(inf)
        today = date.today()
        with open(outfile, 'w') as outf:
            writer = csv.writer(outf)
            writer.writerow(['id', 'fk', 'source', 'last_updated', 'name', 'value'])
            source = 'ppts'
            last_updated = today.isoformat()
            for line in reader:
                id = uuid.uuid4()
                fk = line['record_id']
                for (key,val) in line.items():
                    if val:
                        writer.writerow([id, fk, source, last_updated, key, val])



def dump_and_diff(ppts_file, schemaless_file):
    pass


if __name__ == "__main__":
    csv.field_size_limit(sys.maxsize)

    parser = argparse.ArgumentParser()
    parser.add_argument('ppts_file', help='PPTS file')
    parser.add_argument('out_file', help='output file for schemaless csv')
    parser.add_argument(
        'schemaless_file',
        nargs='?',  # Makes this argument optional
        help='A schemaless csv generated by this script, to diff against.',
        default='')
    args = parser.parse_args()

    if not args.schemaless_file:
        just_dump(args.ppts_file, args.out_file)
    else:
        dump_and_diff(args.ppts_file, args.out_file, args.schemaless_file)
